Repository kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm, pull requests merged in 2019-07, with the labels that each got.

#8 Fix verify-all
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#10 Add GitHub issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7 Generate controllers and api groups
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/kubeadmbootstrapconfig_types.go
  api/v1alpha1/kubeadmbootstrapconfig_types_test.go
  api/v1alpha1/suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kubeadm.bootstrap.cluster.sigs.k8s.io_kubeadmbootstrapconfigs.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_kubeadmbootstrapconfigs.yaml
  config/crd/patches/webhook_in_kubeadmbootstrapconfigs.yaml
  config/rbac/role.yaml
  config/samples/kubeadm_v1alpha1_kubeadmbootstrapconfig.yaml
  config/webhook/manifests.yaml
  controllers/kubeadmbootstrapconfig_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/verify-gotest.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#17 Add bootstrap config fields
  api/v1alpha1/kubeadmbootstrapconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/kubeadmbootstrapconfig_controller.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#20 Add kubeadm constructors
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/kubeadmbootstrapconfig_controller.go
  go.mod
  go.sum
  kubeadm/v1beta1/bootstraptoken.go
  kubeadm/v1beta1/bootstraptoken_test.go
  kubeadm/v1beta1/configs.go
  kubeadm/v1beta1/configs_test.go
  kubeadm/v1beta1/noderegistration.go
  kubeadm/v1beta1/noderegistration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#22 Vendor in kubeadm types
  api/v1alpha1/kubeadmbootstrapconfig_types.go
  api/v1alpha1/kubeadmbootstrapconfig_types_test.go
  config/crd/bases/kubeadm.bootstrap.cluster.sigs.k8s.io_kubeadmbootstrapconfigs.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/fetch_bins.sh
  hack/verify-boilerplate.sh
  hack/verify-gotest.sh
  kubeadm/README.md
  kubeadm/v1beta1/bootstraptoken.go
  kubeadm/v1beta1/bootstraptoken_test.go
  kubeadm/v1beta1/bootstraptokenstring.go
  kubeadm/v1beta1/bootstraptokenstring_test.go
  kubeadm/v1beta1/configs.go
  kubeadm/v1beta1/configs_test.go
  kubeadm/v1beta1/doc.go
  kubeadm/v1beta1/noderegistration.go
  kubeadm/v1beta1/noderegistration_test.go
  kubeadm/v1beta1/types.go
  kubeadm/v1beta1/zz_generated.deepcopy.go
  kubeadm/v1beta2/bootstraptokenstring.go
  kubeadm/v1beta2/bootstraptokenstring_test.go
  kubeadm/v1beta2/doc.go
  kubeadm/v1beta2/types.go
  kubeadm/v1beta2/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#26 Fix json tags on kubeadm types
  config/crd/bases/kubeadm.bootstrap.cluster.sigs.k8s.io_kubeadmbootstrapconfigs.yaml
  kubeadm/v1beta1/bootstraptokenstring.go
  kubeadm/v1beta2/bootstraptokenstring.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#28 Adds some tests and basic controller logic
  controllers/kubeadmbootstrapconfig_controller.go
  controllers/kubeadmbootstrapconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#31 Implement main.go
  Makefile
  go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#40 Fix the linter
  cloudinit/cloudinit.go
  cloudinit/controlplane_certs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#32 initial README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#36 only print failed verfiy outputs
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#30 Controller logic2
  api/v1alpha1/kubeadmbootstrapconfig_types.go
  api/v1alpha1/kubeadmbootstrapconfig_types_test.go
  config-capi/BUILD.bazel
  config-capi/ci/kustomization.yaml
  config-capi/ci/manager/kustomization.yaml
  config-capi/ci/manager_image_patch.yaml
  config-capi/ci/rbac/kustomization.yaml
  config-capi/crds/cluster.k8s.io_clusters.yaml
  config-capi/crds/cluster.k8s.io_machineclasses.yaml
  config-capi/crds/cluster.k8s.io_machinedeployments.yaml
  config-capi/crds/cluster.k8s.io_machines.yaml
  config-capi/crds/cluster.k8s.io_machinesets.yaml
  config-capi/crds/cluster.sigs.k8s.io_clusters.yaml
  config-capi/crds/cluster.sigs.k8s.io_machinedeployments.yaml
  config-capi/crds/cluster.sigs.k8s.io_machines.yaml
  config-capi/crds/cluster.sigs.k8s.io_machinesets.yaml
  config-capi/crds/kustomization.yaml
  config-capi/default/kustomization.yaml
  config-capi/default/manager_image_patch.yaml
  config-capi/manager/kustomization.yaml
  config-capi/manager/manager.yaml
  config-capi/rbac/kustomization.yaml
  config-capi/rbac/role.yaml
  config-capi/rbac/role_binding.yaml
  config-capi/samples/cluster_v1alpha1_cluster.yaml
  config-capi/samples/cluster_v1alpha1_machine.yaml
  config-capi/samples/cluster_v1alpha1_machinedeployment.yaml
  config-capi/samples/cluster_v1alpha1_machineset.yaml
  config-capi/samples/cluster_v1alpha2_cluster.yaml
  config-capi/samples/cluster_v1alpha2_machine.yaml
  config-capi/samples/cluster_v1alpha2_machinedeployment.yaml
  config-capi/samples/cluster_v1alpha2_machineset.yaml
  config-capi/webhook/manifests.yaml
  config/crd/bases/kubeadm.bootstrap.cluster.sigs.k8s.io_kubeadmbootstrapconfigs.yaml
  controllers/kubeadmbootstrapconfig_controller.go
  controllers/kubeadmbootstrapconfig_controller_reconciler_test.go
  controllers/kubeadmbootstrapconfig_controller_test.go
  controllers/suite_test.go
  hack/update-capi-crds.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#38 Use a ready/bool instead of phase
  api/v1alpha1/kubeadmbootstrapconfig_types.go
  config/crd/bases/kubeadm.bootstrap.cluster.sigs.k8s.io_kubeadmbootstrapconfigs.yaml
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#33 Move control plane locker from CAPA
  controllers/control_plane_init_locker.go
  controllers/control_plane_init_locker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#45 fix bug in verify-all script
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#48 Adds certificate generation code pulled from capa
  controllers/certificates.go
  controllers/certificates_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#49 Rename domain
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/kubeadmbootstrapconfig_types.go
  api/v1alpha1/kubeadmbootstrapconfig_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_kubeadmconfigs.yaml
  config/crd/patches/webhook_in_kubeadmconfigs.yaml
  config/rbac/role.yaml
  config/samples/kubeadm_v1alpha1_kubeadmbootstrapconfig.yaml
  config/samples/kubeadm_v1alpha1_kubeadmconfig.yaml
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_reconciler_test.go
  controllers/kubeadmconfig_controller_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#51 Fix for kustomize v3.0
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#53 Enable leader election in manager
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#54 Use PHONY in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S
