Repository kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm, pull requests merged in 2019-09, with the labels that each got.

#204 :warning: Adds encoding field for cloud-init files
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  cloudinit/cloudinit_test.go
  cloudinit/files.go
  cloudinit/utils.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#206 :running: Update Makefile
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#208 Do some code cleaning
  Makefile
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#207 Remove redundant TODOs
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#210 🐛 Fix golangci-lint config to ignore unhelpful lints
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#209 🏃Document tests with minor clean ups
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_reconciler_test.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#216 🏃 Adds a test to reconcile kubeadmconfig based on clusters
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#211 🐛 Test and logic fixes
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#218 📖Fix markdown link.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#220 code clean: controlPane -> controlPlane
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#226 :bug: Fix error-return for machine-cluster association
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#229 :sparkles: Allow restricting namespace for the controller manager
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#230 :sparkles: Add lint to make test command
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#237 :bug: Fix a Machine -> KubeadmConfig mapping bug
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#222 ⚠️ Certificate extraction
  Dockerfile.dev
  certs/certs.go
  certs/certs_test.go
  certs/files.go
  certs/secrets.go
  certs/secrets_test.go
  certs/utils.go
  certs/validate.go
  cloudinit/cloudinit_test.go
  cloudinit/controlplane_init.go
  cloudinit/controlplane_join.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
  go.mod
  go.sum
  internal/cluster/certificates.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#232 🐛 Fix init lock
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#221 🏃‍♂️ Add a test to ensure that exactly one control plane machine initializes if there are multiple control plane machines defined
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#236 ✨ using golangci-lint instead of verify-xxx.sh
  hack/verify-all.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
  hack/verify-govet.sh
  hack/verify-spelling.sh
  hack/verify-whitespace.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#238 Small cleanup for Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#242 Patch kubeadmconfig objects only if no error occurs during reconciliation
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#240 🏃Added Test :Return early if the owning machine does not have an associated cluster
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#251 🏃 Add test for patch behavior
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#256 🏃Add release notes utility / update controller-tools & CRDs
  Makefile
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#257 🏃Align Makefile with other CAP* repos
  Makefile
  cloudbuild.yaml
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#259 🏃Update cluster-api to v0.2.2 and controller-runtime
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#261 :book: Update default behavior for kubernetesVersion field in the readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
