Repository kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm, pull requests merged in 2019-08, with the labels that each got.

#58 Fix jsonpatch in go.sum
  go.sum
  hack/update-deps.sh
  hack/verify-deps.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#61 Use v1alpha2 api version for less user confusion
  .gitignore
  PROJECT
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  api/v1alpha2/kubeadmbootstrapconfig_types_test.go
  api/v1alpha2/suite_test.go
  api/v1alpha2/zz_generated.deepcopy.go
  config-capi/crds/cluster.k8s.io_clusters.yaml
  config-capi/crds/cluster.k8s.io_machineclasses.yaml
  config-capi/crds/cluster.k8s.io_machinedeployments.yaml
  config-capi/crds/cluster.k8s.io_machines.yaml
  config-capi/crds/cluster.k8s.io_machinesets.yaml
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/samples/kubeadm_v1alpha1_kubeadmconfig.yaml
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_reconciler_test.go
  controllers/kubeadmconfig_controller_test.go
  controllers/suite_test.go
  kubeadm/v1beta1/doc.go
  kubeadm/v1beta2/doc.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#66 Enable GOPROXY default in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#72 Fix verify-gofmt
  controllers/kubeadmconfig_controller_reconciler_test.go
  controllers/kubeadmconfig_controller_test.go
  hack/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#67 Add AdditionalUserDataFiles field
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloudinit/cloudinit.go
  cloudinit/controlplane_certs.go
  cloudinit/files.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#75 Always use the right controller-gen
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#69 Switch from Update() to Patch()
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#76 Update to controller-tools v0.2.0-beta.5
  Makefile
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#60 Update approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#42 Generate kubeadm cloud init code
  .gitignore
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloudinit/cloudinit.go
  cloudinit/controlplane_certs.go
  cloudinit/controlplane_init.go
  cloudinit/controlplane_join.go
  cloudinit/node.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  controllers/control_plane_init_locker.go
  controllers/control_plane_init_locker_test.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#83 Fix infrastructure ready
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#79 Fix up image restart process
  Dockerfile
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#84 Update rerun-process-wrapper
  third_party/forked/README.md
  third_party/forked/rerun-process-wrapper/restart.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#87 Fix the docker build
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#89 Bring back AdditionalUserDataFiles
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  api/v1alpha2/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#77 Verify manifests script
  Makefile
  hack/verify-all.sh
  hack/verify-manifests.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#81 Fix machine ref matching
  cloudinit/controlplane_init.go
  cloudinit/controlplane_join.go
  cloudinit/node.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_reconciler_test.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#92 Restore control plane init locker
  controllers/control_plane_init_locker.go
  controllers/control_plane_init_locker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#82 Reconciler loop
  cloudinit/controlplane_join.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_reconciler_test.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#93 Fix verify boilerplate
  Dockerfile
  Makefile
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/boilerplate/boilerplate.Makefile.txt
  hack/boilerplate/boilerplate.bzl.txt
  hack/boilerplate/boilerplate.generatebzl.txt
  hack/boilerplate/boilerplate.generatego.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.py
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/boilerplate/boilerplate_test.py
  hack/boilerplate/test/fail.go
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.go
  hack/boilerplate/test/pass.py
  hack/verify-boilerplate.go
  hack/verify-boilerplate.sh
  hack/verify-boilerplate_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#91 chore: add verify-docker-build.sh
  hack/verify-all.sh
  hack/verify-docker-build.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#96 use AdditionalUserDataFiles in bootstrap data generation
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#103 Set GOPROXY to default if it is not configured
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#95 Refactor: use Patch instead of Update to update a config
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#107 Defer the patch
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#106 Use CAPI utils to reduce boilerplate
  controllers/control_plane_init_locker_test.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#110 chore: get kubeadm yaml rather than json
  controllers/kubeadmconfig_controller.go
  go.sum
  kubeadm/v1beta1/groupversion_info.go
  kubeadm/v1beta1/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#115 chore: initialize klog flags
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#119 Use same logger throughout the codebase
  api/v1alpha2/suite_test.go
  controllers/control_plane_init_locker_test.go
  controllers/kubeadmconfig_controller_reconciler_test.go
  controllers/kubeadmconfig_controller_test.go
  controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#117 Add kubebuilder markers to CRDs for status and namespace
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#104 Update Makefile that runs generates to use the generate boilerplate instead of the go boilerplate
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#120 Update control-plane label value as cabpk-controller-manager
  config-capi/manager/manager.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
  config/webhook/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#118 Streamline make generate
  Makefile
  hack/verify-manifests.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#124 Remove gvk hack from deferred patch
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#105 Reconcile automatically create join token if necessary
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
  controllers/token.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#126 Add certificate generation and secret lookup to bootstrap controller
  Dockerfile
  Makefile
  certs/certs.go
  certs/certs_test.go
  certs/files.go
  certs/utils.go
  certs/validate.go
  cloudinit/controlplane_init.go
  cloudinit/controlplane_join.go
  config/rbac/role.yaml
  controllers/certificates_test.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#130 Set the args in the manager_auth_proxy_patch.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#136 chore: kubeconfig as secret
  certs/certs.go
  certs/utils.go
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#134 Clean up some misleading logs
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#137 Fix manager rbac permission
  config/rbac/role.yaml
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#122 Only one node should do kubeadm init
  controllers/control_plane_init_locker.go
  controllers/control_plane_init_locker_test.go
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#139 Handle setting of ClusterConfiguration.ClusterName
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#140 chore: add rbac for configmaps
  config/rbac/role.yaml
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#128 AdditionalCommands support in kubeadm spec
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloudinit/cloudinit.go
  cloudinit/controlplane_init.go
  cloudinit/controlplane_join.go
  cloudinit/node.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#141 Reconcile top most level objects
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#142 chore: add omitempty to fields
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  kubeadm/v1beta1/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#145 chore: add KubeadmConfigTemplate type
  PROJECT
  api/v1alpha2/kubeadmconfigtemplate_types.go
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_kubeadmconfigtemplates.yaml
  config/crd/patches/webhook_in_kubeadmconfigtemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#148 Use patch helper from cluster-api
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  controllers/control_plane_init_locker.go
  controllers/control_plane_init_locker_test.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
  controllers/suite_test.go
  controllers/token.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#150 chore: release lock from correct namespace
  config/rbac/role.yaml
  controllers/control_plane_init_locker.go
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#151 add capi categories
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#152 :bug: Comment out empty patches
  config/crd/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#146 Format field in KubeadmConfig.Spec
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  hack/verify-manifests.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#156 Mark kubeadm optional fields with +optional
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  kubeadm/v1beta1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#159 allow for time skew in cert generation
  certs/certs.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#162 Remove unused rootOwnerValue constant
  cloudinit/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#163 Disambiguate v1 import
  kubeadm/v1beta2/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#155 add ErrorReason/ErrorStatus to CRD statuses
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#164 Remove unused isKeyPairValid function
  cloudinit/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#172 Add 'help' target to Makefile and make it the default
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#171 Rename type Files to File
  api/v1alpha2/kubeadmbootstrapconfig_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  certs/files.go
  cloudinit/cloudinit.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#174 fix write files for worker nodes
  cloudinit/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#181 ✨ Add multi-arch docker targets support
  Dockerfile
  Dockerfile.dev
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#184 ✨ Add github action to push on master merge
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#170 📖 Update Documentation
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#165 ✨ enable golangci-lint
  .golangci.yml
  Makefile
  cloudinit/controlplane_test.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify-all.sh
  hack/verify-golangci-lint.sh
  internal/locking/control_plane_init_mutex_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#178 ✨Watch Machine and Cluster in kubeadmconfig controller
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_reconciler_test.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#177 ✨ Calculate cert hashes and verify CA certificates
  certs/utils.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#186 :warning: No embedded object meta
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#187 :sparkles: Add tag to action, update Makefile
  .github/workflows/main.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#188 🐛 Fix a Cluster -> KubeadmConfig mapper bug
  config/rbac/role.yaml
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#189 🏃‍♂️ Name v1alpha2 imports
  certs/files.go
  cloudinit/cloudinit.go
  controllers/kubeadmconfig_controller_reconciler_test.go
  controllers/kubeadmconfig_controller_test.go
  controllers/suite_test.go
  controllers/token.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#191 🐛Fix NPE when looking at Cluster Network fields
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#194 🐛 Fix development dockerfile
  Dockerfile.dev
Labels: approved, cncf-cla: yes, lgtm, size/XS

#196 :sparkles: Add cluster-api group to KubeadmConfigTemplate
  api/v1alpha2/kubeadmconfigtemplate_types.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#195 ✨ Make Manager SyncPeriod configurable via flag
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#198 ⚠️ Remove kubeconfig generation
  certs/certs.go
  certs/utils.go
  controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#197 :warning: Switch to 1 secret per certificate
  Makefile
  certs/certs.go
  certs/secrets.go
  certs/secrets_test.go
  certs/utils.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#199 :running: Update to controller-tools v0.2.0
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#200 🏃 Add release targets
  .github/workflows/main.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M
