Repository kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm, pull requests merged in 2019-10, with the labels that each got.

#234 ✨ Initialize JoinConfiguration if missing
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#260 ✨ Adds support for external etcd & respects custom certificates directory from kubeadm
  cloudinit/cloudinit_test.go
  cloudinit/controlplane_init.go
  cloudinit/controlplane_join.go
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
  docs/external-etcd.md
  internal/cluster/certificates.go
  internal/cluster/certificates_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#253 🎉 Promote @sataqiu to a maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#263 🐛 Separate certificate logic for joins
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
  internal/cluster/certificates.go
  internal/cluster/certificates_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#250 🐛 Refresh token for provisioning machines
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
  controllers/token.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#267 fix: ensure there's a token to refresh
  controllers/kubeadmconfig_controller.go
  controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#270 add well-known tolerations to released CABPK components
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#269 🏃Update module dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#273 🐛 Support running alongside other Cluster API pods in the same namespace with leader election enabled
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#279 :running: Update controller runtime, Go 1.12, Cluster API v0.2.5
  Dockerfile
  Dockerfile.dev
  api/v1alpha2/zz_generated.deepcopy.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#280 🐛 Fixes an issue where KubeadmConfig Pre/PostKubeadmCommands were not being properly escaped
  cloudinit/cloudinit_test.go
  cloudinit/commands.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#283 fix unmarshal err for blank field
  internal/locking/control_plane_init_mutex.go
Labels: approved, cncf-cla: yes, lgtm, size/S
